import Head from "next/head"
import Link from "next/link"
import Image from "next/image"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <a href="/serversidePost" className={styles.card}>
            <h2>SSR: Server-side rendering &rarr;</h2>
            <p>
              Using SSR with <span>getServerSideProps</span>
            </p>
          </a>

          <a href="/staticsitePost" className={styles.card}>
            <h2>SSG: Static-site generation &rarr;</h2>
            <p>Using SSG with getStaticProps</p>
          </a>

          <a href="/clientsidePost" className={styles.card}>
            <h2>CSR: Client-side rendering &rarr;</h2>
            <p>Using CSR with SWR</p>
          </a>

          <a href="/api" className={styles.card}>
            <h2>API &rarr;</h2>
            <p>Using API</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
